In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.54395823])

In [10]:
np.random.rand(25)

array([0.19533547, 0.00898037, 0.21101975, 0.53949937, 0.55720935,
       0.13953693, 0.12365403, 0.35555591, 0.48745203, 0.27241756,
       0.99894858, 0.01278199, 0.95753798, 0.27559513, 0.07249799,
       0.93270538, 0.35437319, 0.60063943, 0.53198862, 0.71724419,
       0.96512047, 0.01286153, 0.49046535, 0.1734685 , 0.57343102])

In [11]:
np.linspace(0.01,1,10)

array([0.01, 0.12, 0.23, 0.34, 0.45, 0.56, 0.67, 0.78, 0.89, 1.  ])

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
ar = np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
ar[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [16]:
ar = np.arange(1,26).reshape(5,5)
ar[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [17]:
ar=np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
ar[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
ar[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [20]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat[0:3,1:2]


array([[ 2],
       [ 7],
       [12]])

In [22]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [23]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
np.sum(mat)

325

In [25]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [26]:
arr=np.arange(0,12).reshape(3,2,2)
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.dtype

dtype('int32')

In [29]:
v=np.random.randint(1,100,20).reshape(4,5)
v

array([[51, 72, 10, 82, 65],
       [81,  1, 31, 44, 30],
       [89, 18, 56, 98, 32],
       [41, 62, 49, 33, 92]])

In [30]:
asc=np.sort(v)
asc

array([[10, 51, 65, 72, 82],
       [ 1, 30, 31, 44, 81],
       [18, 32, 56, 89, 98],
       [33, 41, 49, 62, 92]])

In [31]:
#asending order
np.flip(v)

array([[92, 33, 49, 62, 41],
       [32, 98, 56, 18, 89],
       [30, 44, 31,  1, 81],
       [65, 82, 10, 72, 51]])

In [32]:
np.copy(v)

array([[51, 72, 10, 82, 65],
       [81,  1, 31, 44, 30],
       [89, 18, 56, 98, 32],
       [41, 62, 49, 33, 92]])

In [33]:
np.flip(asc)

array([[92, 62, 49, 41, 33],
       [98, 89, 56, 32, 18],
       [81, 44, 31, 30,  1],
       [82, 72, 65, 51, 10]])

In [34]:
np.copy(v)

array([[51, 72, 10, 82, 65],
       [81,  1, 31, 44, 30],
       [89, 18, 56, 98, 32],
       [41, 62, 49, 33, 92]])

In [35]:
vcopy=np.copy(v)
vcopy

array([[51, 72, 10, 82, 65],
       [81,  1, 31, 44, 30],
       [89, 18, 56, 98, 32],
       [41, 62, 49, 33, 92]])

In [36]:
vcopy [:5] = 99
vcopy

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [37]:
v

array([[51, 72, 10, 82, 65],
       [81,  1, 31, 44, 30],
       [89, 18, 56, 98, 32],
       [41, 62, 49, 33, 92]])

In [38]:
iden = np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
iden.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [40]:
mat =  np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
np.vsplit(mat,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [43]:
np.hsplit(mat,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [44]:
np.hstack((mat,[[12],[13],[14]]))

array([[ 0,  1,  2, 12],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14]])

In [45]:
np.eye(4)+6

array([[7., 6., 6., 6.],
       [6., 7., 6., 6.],
       [6., 6., 7., 6.],
       [6., 6., 6., 7.]])

In [46]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
#genrate floting values
rarr=np.random.uniform(0,15,10)
rarr

array([ 6.82742023,  7.00345149,  9.24513942, 13.316016  ,  4.83263728,
        3.81176922,  3.07632253,  0.12850846,  9.8377313 ,  3.70053132])

In [48]:
np.ceil(rarr) 

array([ 7.,  8., 10., 14.,  5.,  4.,  4.,  1., 10.,  4.])

In [49]:
np.round(rarr,decimals=2)

array([ 6.83,  7.  ,  9.25, 13.32,  4.83,  3.81,  3.08,  0.13,  9.84,
        3.7 ])

In [50]:
np.floor(rarr)

array([ 6.,  7.,  9., 13.,  4.,  3.,  3.,  0.,  9.,  3.])

In [51]:
v=np.arange(0,25).reshape(5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
np.sum(v)

300

In [53]:
np.sum(v,axis=0)

array([50, 55, 60, 65, 70])

In [54]:
np.min(v,axis=0)

array([0, 1, 2, 3, 4])

In [55]:
np.max(v,axis=0)

array([20, 21, 22, 23, 24])

In [56]:
np.var(v,axis=0)

array([50., 50., 50., 50., 50.])

In [57]:
np.std(v,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [58]:
nv=np.full(10,'NaN')
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [59]:
nv[5]=200
nv

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', '200', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [60]:
np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7], dtype=int32),)

In [61]:
vr=np.arange(100,151)
vr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [62]:
np.flip(vr)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [63]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
v=np.ones(100).reshape(10,10)
v

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
v[1:9,1:9]=0

In [66]:
v

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
vr=np.ones(64).reshape(8,8)
vr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [68]:
vr[::2,::2]=1
vr[1::2,1::2]=0
vr


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])